button.place.secure.payment=Place secure payment
creditCardPayment.allow.pay=Pay with Credit card
payment.wallet.submit.info=*Please note: Once you select the selected wallet payment button below - your payment will be taken
pay.with.wallet=Pay with Wallet
button.back.to.checkout=Back to checkout

## Reccuring
checkout.reccuring.error.disabled=Cart is not eligible. Subscription feature is disabled
checkout.reccuring.error.limit=Cart is not eligible. Not allowed to create order with more then 1 subscription.
checkout.reccuring.error.not.eligible=Cart is not eligible. Not allowed to create order with regular products and subscription.
checkout.reccuring.error.not.logged.in=Customer must be logged in to complete recurring checkout
