## Recurring
subscriptions.title=Subscriptions
subscriptions.item.details={0} {1} Next billing: {2}
subscriptions.item.details.action.cancel=Cancel
subscriptions.item.details.status.canceled=Canceled
subscriptions.view.all=View all
