partialsettle.order = Settle Amount
partialrefund.order = Refund

# Error Messages
csc.error.query.payment.status = Failed to query payment status
csc.error.action.link.not.found = {0} link not found in payment details
csc.error.settle.order = Failed to settle the order
csc.error.settle.use.partial = Cannot settle full amount when partial amounts exist
csc.error.partial.settle.order = Failed to partially settle the order
csc.error.partial.settle.invalid=Invalid refund amount
csc.error.partial.refund.order = Failed to partially refund the order
csc.error.refund.order = Failed to refund the order
csc.error.refund.use.partial = Cannot refund full amount when partial amounts exist
csc.error.invalid.access.request.type = Invalid accessReqType parameter
csc.error.partial.pending = Cannot process partial refund/settle when previous partial refund/settle is pending

# Success Messages
csc.success.settle.order = Order settled successfully
csc.success.partial.settle.order = Order partially settled successfully
csc.success.partial.refund.order = Order partially refunded successfully
csc.success.refund.order = Order refunded successfully
csc.success.payment.status.retrieved = Payment status retrieved successfully