worldpay.paymentmethodtype.worldpay = Hosted Payment Page
worldpay.paymentmethod.heading = Select Payment Method
worldpay.saved.cards=Saved cards
worldpay.delete.card=Delete

awp.cancelled=Payment was cancelled.
awp.error=Payment error. Please try again.
awp.expired=Payment session expired.
awp.failed=Payment failed.
