## cartridge.properties for cartridge worldpay_access
#Wed Jun 30 13:22:34 CEST 2025
demandware.cartridges.int_worldpay_access.multipleLanguageStorefront=true
demandware.cartridges.int_worldpay_access.id=int_worldpay_access